[supervisord]
nodaemon=true
logfile=/var/www/html/var/logs/supervisord.log
pidfile=/tmp/supervisord.pid

[program:messenger-email]
command=php /var/www/html/bin/console messenger:consume email --env=prod --time-limit=3600 --limit=100
user=www-data
autostart=true
autorestart=true
numprocs=%(ENV_DOCKER_MAUTIC_WORKERS_CONSUME_EMAIL)s
process_name=%(program_name)s_%(process_num)02d
redirect_stderr=true
stdout_logfile=/var/www/html/var/logs/messenger-email.log

[program:messenger-hit]
command=php /var/www/html/bin/console messenger:consume hit --env=prod --time-limit=3600 --limit=100
user=www-data
autostart=true
autorestart=true
numprocs=%(ENV_DOCKER_MAUTIC_WORKERS_CONSUME_HIT)s
process_name=%(program_name)s_%(process_num)02d
redirect_stderr=true
stdout_logfile=/var/www/html/var/logs/messenger-hit.log

[program:messenger-failed]
command=php /var/www/html/bin/console messenger:consume failed --env=prod --time-limit=3600 --limit=100
user=www-data
autostart=true
autorestart=true
numprocs=%(ENV_DOCKER_MAUTIC_WORKERS_CONSUME_FAILED)s
process_name=%(program_name)s_%(process_num)02d
redirect_stderr=true
stdout_logfile=/var/www/html/var/logs/messenger-failed.log
